baseURL = "https://adventurefordementia.com"
languageCode = "en-gb"
title = "Adventure For Dementia"
theme = "afd"
disableKinds = ["RSS", "sitemap"]
disableHugoGeneratorInject = true

[params]
metaDescription = "Follow James and Aaron as they travel 10,000 miles from Sussex to Mongolia"
longTitle = "Adventure For Dementia - Mongol Rally 2015 Team"

[markup.goldmark.renderer]
unsafe = true
