[build]
  command = "hugo --minify"
  publish = "public"

[[redirects]]
  from = "/update"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' *.cloudfront.net; font-src 'self'; frame-src www.google.com;"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "SAMEORIGIN"
      X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
    [headers.values]
      Cache-control = "public, max-age=604800"

[[headers]]
  for = "/assets/fonts/*"
    [headers.values]
      Cache-control = "public, max-age=31536000"
